services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - server