name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Trigger workflow on merge to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment for building the React app
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # Step 3: Install the correct version of Yarn (based on package.json)
      - name: Install Corepack (for Yarn v4+)
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate

      # Step 3: Install dependencies for React app (in client folder)
      - name: Install dependencies for React
        run: |
          cd client
          yarn install

      # Step 4: Build the React app
      - name: Build React app
        run: |
          cd client
          yarn build

      # Step 5: Move the build folder to the server/ directory
      - name: Move build folder to server
        run: |
          mv client/build server/build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 7: Checkout the deploy branch
      - name: Checkout deploy branch
        uses: actions/checkout@v3
        with:
          ref: deploy

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git config user.name "Zhuoheng Li"
          git config user.email "<cynayd@gmail.com>"
          cd server
          git init
          git remote add heroku https://git.heroku.com/focusambiguity.git
          git add .
          git commit -m "Deploy server to Heroku"
          git push heroku master --force
